import streamlit as st
import pandas as pd
import pickle
import os
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score, 
    recall_score, f1_score, matthews_corrcoef, 
    confusion_matrix, classification_report
)
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# 1. Page Configuration & Header
# ==========================================
st.set_page_config(
    page_title="E-Commerce ML Dashboard", 
    page_icon="🛒", 
    layout="wide"
)

st.title("🛒 E-Commerce Customer Purchase Intention & Model Evaluation Dashboard")

# The newly added Project & Dataset Description Expander
with st.expander("ℹ️ About This Project & Dataset", expanded=True):
    st.markdown("""
    * **Task Overview:** This is a binary classification task designed to predict e-commerce customer purchase intent (`Revenue`). It analyzes user browsing behavior, session durations, page values, and traffic telemetry to determine whether a visitor will complete a purchase (`1`) or leave without buying (`0`).
    * **Dataset Source:** The dataset used is the **Online Shoppers Purchasing Intention Dataset** obtained from the **UCI Machine Learning Repository**.
    * **Evaluation Suite:** An end-to-end Machine Learning web dashboard evaluating **5 different classifiers** (Logistic Regression, Decision Tree, kNN, Naive Bayes, Random Forest) across **6 key metrics** (Accuracy, AUC, Precision, Recall, F1, and MCC).
    * **Data Loading & Upload:** The app automatically loads the default test dataset (`test_data.csv`) that was generated and prepared during our pipeline execution. Additionally, a fully functional **sidebar CSV upload widget** is provided, allowing you to upload and evaluate custom test datasets at any time.
    """)

st.markdown("---")

# ==========================================
# 2. Sidebar: Model Selection & Data Upload
# ==========================================
st.sidebar.header("⚙️ Evaluation Settings")

# Model Selector
model_choice = st.sidebar.selectbox(
    "Select a Machine Learning Model",
    ["Logistic Regression", "Decision Tree", "kNN", "Naive Bayes", "Random Forest"]
)

# File Uploader
st.sidebar.markdown("### 📁 Upload Custom Test Data")
uploaded_file = st.sidebar.file_uploader("Upload CSV file (Optional)", type=["csv"])

# ==========================================
# 3. Data Loading Logic
# ==========================================
@st.cache_data
def load_data(file):
    return pd.read_csv(file)

try:
    if uploaded_file is not None:
        df = load_data(uploaded_file)
        st.sidebar.success("✅ Custom dataset loaded successfully!")
    else:
        # Fallback to default test dataset generated by train.py
        df = load_data("test_data.csv")
        st.sidebar.info("ℹ️ Using default generated test dataset.")
except FileNotFoundError:
    st.error("🚨 `test_data.csv` not found. Please upload a dataset using the sidebar or run `train.py` to generate it.")
    st.stop()

# Separate features and target (Assuming 'Revenue' is the target column)
if 'Revenue' not in df.columns:
    st.error("🚨 The dataset must contain a 'Revenue' column as the target variable.")
    st.stop()

X_test = df.drop(columns=['Revenue'])
y_test = df['Revenue']

# ==========================================
# 4. Model Loading Logic
# ==========================================
model_files = {
    "Logistic Regression": "model/logistic_regression.pkl",
    "Decision Tree": "model/decision_tree.pkl",
    "kNN": "model/knn.pkl",
    "Naive Bayes": "model/naive_bayes.pkl",
    "Random Forest": "model/random_forest.pkl"
}

@st.cache_resource
def load_pickle(file_path):
    with open(file_path, "rb") as f:
        return pickle.load(f)

try:
    # Load the selected model
    model = load_pickle(model_files[model_choice])
    
    # Scale features for models that require scaling (Logistic Regression & kNN)
    if model_choice in ["Logistic Regression", "kNN"]:
        scaler = load_pickle("model/scaler.pkl")
        X_test_processed = scaler.transform(X_test)
    else:
        X_test_processed = X_test

except FileNotFoundError as e:
    st.error(f"🚨 Model file not found: {e}. Please ensure you have run `train.py` to generate the `.pkl` files in the `model/` directory.")
    st.stop()

# ==========================================
# 5. Predictions & Metrics Calculations
# ==========================================
y_pred = model.predict(X_test_processed)

# Calculate predict_proba for AUC (handling models that might not support it directly)
if hasattr(model, "predict_proba"):
    y_proba = model.predict_proba(X_test_processed)[:, 1]
    auc = roc_auc_score(y_test, y_proba)
else:
    auc = roc_auc_score(y_test, y_pred) # Fallback

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
mcc = matthews_corrcoef(y_test, y_pred)

# ==========================================
# 6. Dashboard Display (Matching Screenshots)
# ==========================================
st.subheader(f"Evaluation Results for: {model_choice}")

# Display Metrics in 6 Columns
col1, col2, col3, col4, col5, col6 = st.columns(6)
col1.metric("Accuracy", f"{accuracy:.4f}")
col2.metric("AUC Score", f"{auc:.4f}")
col3.metric("Precision", f"{precision:.4f}")
col4.metric("Recall", f"{recall:.4f}")
col5.metric("F1 Score", f"{f1:.4f}")
col6.metric("MCC Score", f"{mcc:.4f}")

st.markdown("---")

# Layout for Visualizations
viz_col1, viz_col2 = st.columns(2)

# Confusion Matrix Heatmap
with viz_col1:
    st.markdown("### Confusion Matrix")
    cm = confusion_matrix(y_test, y_pred)
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=True, ax=ax)
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    st.pyplot(fig)

# Classification Report Table
with viz_col2:
    st.markdown("### Classification Report")
    report_dict = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    report_df = pd.DataFrame(report_dict).transpose()
    
    # Format to 4 decimal places just like the screenshots
    st.dataframe(report_df.style.format("{:.4f}"), use_container_width=True)